const signature = '_____________________________sexsesexsexsexsexsexs \n' +
'_____________________________sexsexsexsexsexsexsexse \n' +
'___________________________sexsexsexsexsexsexsexsexsex \n' +
'_________________________sexsexsexsexsexsexsexsexsexsex \n' +
'________________________sexsexsexsexsexsexsexsexsexsexs \n' +
'_______________________sexsexsexsexsexsexsexsexsexsexsex \n' +
'______________________sexsexsexsexsexsexsexsexsexsexsexse \n' +
'_____________________sexsexsexsexsexsexsexsexsexsexsexsex \n' +
'_____________________exsexsexsexsexsexsexsex__sexsexsexsex \n' +
'____________________sexsexsexsexsexsexsexs_____sexsexsexse \n' +
'____________________sexsexsexsexsexsexsex________sexsexsex \n' +
'____________________sexsexsexsexsexsex____________sexsexsx \n' +
'____________________sexsexsexsexsexx______________sexsexs_x \n' +
'____________________sexsexsexsexsex-****.____.***-sexsexs_sexs \n' +
'____________________sexsexsexsexsex_______________sexsex_sexsexs \n' +
'____________________sexsexsexsexsex______________sexsex_sexsexsexs \n' +
'____________________sexsexsexsexsex______________sexse_sexsexsexse \n' +
'____________________sesexsexsexsexs___--sexsex-_sexse_sexsexsexse \n' +
'____________________xsexsexsexsexse______sexs__sexse_sexsexsexs \n' +
'___________________sexsexsexsexsexse_________sexse_sexsexsexse \n' +
'_________________sexsexsexsexsexsexs_______sexse____sexsexse \n' +
'________________sexsexse______sexsexs______ixx_______sexse \n' +
'________________sexsex_________sexsexs_____i_________sex \n' +
'________________sexs____________sexsexs____i_________x \n' +
'________________sex______________sexsex________x___x \n' +
'_________________x_______________sexsex________x__x \n' +
'________________x________________sexse__________xx \n' +
'______________sex________________sex________________x \n' +
'____________sexsexs_____________xx_____________________x \n' +
'___________sexsexsex____x_x__________________x___________x \n' +
'_________sexsexsexsexse_______________________x__________(o \n' +
'_______sexsexsexsexse_______x____________________________x \n' +
'_____sexsexsexsexse___x_____x_________(o)______x________x \n' +
'___sexsexsexsexse_____x______x_________________x_______x \n' +
'__sexsexsexsex________x_______x_______________x______x \n' +
'sexsexsexsex__________x________x_____________x____xx \n' +
'sexsexsexse___________x__________x_________x______x \n' +
'_sexsexsexse___________x___________x_x__x_________x \n' +
'___sexsexsexs__________x__________________________x \n' +
'____sexsexsexs__________x________________________x \n' +
'_____sexsexsex___________x_______________________x \n' +
'______sexsexsex___________x_____________________x \n' +
'_______sexsexsex___________x____________________x \n' +
'_________sexsexse____________x_________________x \n' +
'__________sexsexse____________x________________x \n' +
'____________sexsexs___________x_________________x \n' +
'______________sexsex_sexsexse_x__________________x \n' +
'_______________sexsexsexsexsexs___________________x \n' +
'_________________sexsexsexsexse_____________________x \n' +
'__________________sexsexsexsex_______________o_______x \n' +
'_______________________sexsex________________________x \n' +
'________________________x_____________________________x \n' +
'_______________________x______________________________x \n' +
'______________________x_______________________________x \n' +
'______________________x______________________Y________x \n' +
'______________________x______________________x________x \n' +
'______________________x_______________________x_______x \n' +
'______________________x________________________x______x \n' +
'______________________x_________________sexsexsex_____x \n' +
'______________________x____________sexsexsexsexsx_exsex \n' +
'______________________x__________sexsex=aluke=exs_sexx \n' +
'_______________________x_______sexsexse=aluke=sexs_xx \n' +
'________________________x_____sexsexsex=aluke=exse_x \n' +
'_________________________x___sexsexsexsexsexsexsexs \n' +
'__________________________x_sexsexsexsexsexsexsexse \n' +
'____________________________sexsexsexsexsexsexsexsex \n' +
'_____________________________sexsexsexsexsexsexsexse \n' +
'____________________________x_sexsexsexsexsexsexsexs \n' +
'____________________________xx_sexsexsexsexsexsexsexs \n' +
'____________________________sex_sexsexsexsexsexsexsex \n' +
'_____________________________sex_sexsexsexsexsexsexse \n' +
'_____________________________sexs_sexsexsexsexsexsexs \n' +
'______________________________sexse_sexsexsexsexsexse \n';

export default signature;
